# Generated by Django 3.0.7 on 2020-06-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('listing_type', models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('commercial', 'commercial'), ('office', 'office'), ('land', 'land')], max_length=30, null=True)),
                ('date_built', models.DateTimeField(null=True)),
            ],
        ),
    ]
