# Generated by Django 3.0.7 on 2020-06-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200615_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='property_price',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
