# Generated by Django 3.0.7 on 2020-06-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200615_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amentities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amentity', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='amentities',
            field=models.ManyToManyField(to='properties.Amentities'),
        ),
    ]
