# Generated by Django 3.0.7 on 2020-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20200615_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
