# Generated by Django 3.0.7 on 2020-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_uploadproperties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='plot_of_land',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
