# Generated by Django 3.0.7 on 2020-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_uploadproperties_plot_of_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='property_main_img',
            field=models.ImageField(null=True, upload_to='media/properties_img/'),
        ),
    ]
