# Generated by Django 3.0.7 on 2020-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_uploadproperties_property_main_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadproperties',
            name='property_main_img',
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='property_image2',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='property_image3',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='property_image4',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='property_image5',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='property_main_image',
            field=models.ImageField(null=True, upload_to='properties_images/'),
        ),
    ]
