# Generated by Django 3.0.7 on 2020-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200615_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='office_space',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
