# Generated by Django 3.0.7 on 2020-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_uploadproperties_office_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='tag',
            field=models.CharField(choices=[('featured', 'featured'), ('popular', 'popular')], max_length=10, null=True),
        ),
    ]
