# Generated by Django 3.0.7 on 2020-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_uploadproperties_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_image4',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_image5',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
    ]
