# Generated by Django 3.0.7 on 2020-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20200615_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
    ]
