# Generated by Django 3.0.7 on 2020-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_auto_20200615_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='payment_condition',
            field=models.CharField(choices=[('yearly', 'yearly'), ('monthly', 'monthly')], max_length=30, null=True),
        ),
    ]
