# Generated by Django 3.0.7 on 2020-06-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_uploadproperties_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='bed',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=None, max_length=10, null=True),
        ),
    ]
