# Generated by Django 3.0.7 on 2020-06-17 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_uploadproperties_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadproperties',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
