# Generated by Django 3.0.7 on 2020-06-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_uploadproperties_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadproperties',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='uploadproperties',
            name='time_uploaded',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
