# Generated by Django 3.0.7 on 2020-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20200617_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='time_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
