# Generated by Django 3.0.7 on 2020-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=300, null=True),
        ),
    ]
