# Generated by Django 3.0.7 on 2020-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20200618_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
