# Generated by Django 3.0.7 on 2020-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='listing_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Office', 'Office'), ('Land', 'Land')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='security',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='tag',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Popular', 'Popular')], max_length=10, null=True),
        ),
    ]
