# Generated by Django 3.0.7 on 2020-06-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_auto_20200619_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('commercial', 'commercial'), ('office', 'office'), ('land', 'land')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='security',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadproperties',
            name='tag',
            field=models.CharField(choices=[('featured', 'featured'), ('popular', 'popular')], max_length=10, null=True),
        ),
    ]
