# Generated by Django 3.0.7 on 2020-06-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_auto_20200622_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadproperties',
            name='bed',
        ),
    ]
