# Generated by Django 3.0.7 on 2020-06-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_remove_uploadproperties_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_state', models.CharField(choices=[('Abuja', 'Abuja'), ('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nassarawa', 'Nassarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=15, null=True)),
                ('company_logo_light', models.ImageField(null=True, upload_to='company_logo/')),
                ('company_logo_dark', models.ImageField(null=True, upload_to='company_logo/')),
                ('company_phone_number1', models.CharField(max_length=300, null=True)),
                ('company_phone_number2', models.CharField(max_length=300, null=True)),
                ('company_address', models.CharField(max_length=300, null=True)),
                ('company_email', models.EmailField(max_length=254, null=True)),
                ('company_facebook_link', models.CharField(max_length=300, null=True)),
                ('company_twitter_link', models.CharField(max_length=300, null=True)),
                ('company_whatsapp_link', models.CharField(max_length=300, null=True)),
                ('company_iinstagram_link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image1', models.ImageField(null=True, upload_to='homepage_images/')),
                ('slide_image2', models.ImageField(null=True, upload_to='homepage_images/')),
                ('slide_image3', models.ImageField(null=True, upload_to='homepage_images/')),
                ('slide_image4', models.ImageField(null=True, upload_to='homepage_images/')),
                ('company_image', models.ImageField(null=True, upload_to='homepage_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, null=True)),
                ('partner_logo', models.ImageField(null=True, upload_to='partners_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('client_career', models.CharField(max_length=200, null=True)),
                ('client_image', models.ImageField(null=True, upload_to='clients_images/')),
                ('client_comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200, null=True)),
                ('staff_image', models.ImageField(null=True, upload_to='staff_image/')),
                ('staff_phoneNumber', models.CharField(max_length=15, null=True)),
                ('staff_position', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
