# Generated by Django 3.0.7 on 2020-06-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_companyinfo_homepageimages_partners_testmonials_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
