# Generated by Django 3.0.7 on 2020-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_companyinfo_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmonials',
            name='client_image',
            field=models.ImageField(default='img.jpg', null=True, upload_to='clients_images/'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='staff_image',
            field=models.ImageField(default='img.jpg', null=True, upload_to='staff_image/'),
        ),
    ]
