# Generated by Django 3.0.7 on 2020-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_auto_20200626_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimages',
            name='company_image',
            field=models.ImageField(default='media-demo/banner/banner-1.jpg', null=True, upload_to='homepage_images/'),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='slide_image1',
            field=models.ImageField(default='media-demo/banner/banner-1.jpg', null=True, upload_to='homepage_images/'),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='slide_image2',
            field=models.ImageField(default='media-demo/banner/banner-1.jpg', null=True, upload_to='homepage_images/'),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='slide_image3',
            field=models.ImageField(default='media-demo/banner/banner-1.jpg', null=True, upload_to='homepage_images/'),
        ),
        migrations.AlterField(
            model_name='homepageimages',
            name='slide_image4',
            field=models.ImageField(default='media-demo/banner/banner-1.jpg', null=True, upload_to='homepage_images/'),
        ),
    ]
