# Generated by Django 3.0.7 on 2020-06-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_auto_20200626_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_iinstagram_link',
            new_name='company_instagram_link',
        ),
    ]
