# Generated by Django 3.0.7 on 2020-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_auto_20200626_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_logo_dark',
            field=models.ImageField(default='assets/anotherlogo1.png', null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_logo_light',
            field=models.ImageField(default='assets/anotherlogo.png', null=True, upload_to='company_logo/'),
        ),
    ]
