# Generated by Django 3.0.7 on 2020-06-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_auto_20200626_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInfo',
            new_name='Companyinformation',
        ),
    ]
