# Generated by Django 3.0.7 on 2020-07-06 13:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_auto_20200626_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmonials',
            name='client_comment',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
