# Generated by Django 3.0.7 on 2020-07-16 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_auto_20200716_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
