# Generated by Django 3.0.7 on 2020-07-16 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_auto_20200716_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
