# Generated by Django 3.0.7 on 2020-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_auto_20200716_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='property_title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
