# Generated by Django 3.0.7 on 2020-07-17 09:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_auto_20200717_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadproperties',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
